"""Columns for speech

Revision ID: 29555b566e72
Revises: 1db7f3eeb959
Create Date: 2018-12-05 20:01:31.182757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29555b566e72'
down_revision = '1db7f3eeb959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.drop_column('audio_url')
        batch_op.drop_column('audio_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_filename', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('audio_url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
