"""Re-created migrations

Revision ID: 73aa63e79620
Revises: 
Create Date: 2018-03-09 12:23:04.664106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73aa63e79620'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_texts_timestamp'), 'texts', ['timestamp'], unique=False)
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=True),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('themes')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_texts_timestamp'), table_name='texts')
    op.drop_table('texts')
    # ### end Alembic commands ###
