"""Updated backref error

Revision ID: 7e5191cbcc70
Revises: fa4b219c2134
Create Date: 2018-03-07 16:59:19.788164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5191cbcc70'
down_revision = 'fa4b219c2134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('sentence', sa.Text(), nullable=True))
    op.drop_column('sentences', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('text', sa.TEXT(), nullable=True))
    op.drop_column('sentences', 'sentence')
    # ### end Alembic commands ###
