"""Added text to speech

Revision ID: 81909ee9419d
Revises: 29555b566e72
Create Date: 2018-12-06 00:54:56.779487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81909ee9419d'
down_revision = '29555b566e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_audio_text", 'texts', ['text_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
