"""Fixed foreign key and renamed themes

Revision ID: fa4b219c2134
Revises: ceef0f9dc08a
Create Date: 2018-03-07 16:56:38.482953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4b219c2134'
down_revision = 'ceef0f9dc08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('predictions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predictions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('theme', sa.TEXT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('sentence_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('themes')
    # ### end Alembic commands ###
